In [27]:
!pip install requests
!conda install requests
import requests
import pandas as pd

Requirement already satisfied: requests in /Users/maddonk/anaconda3/lib/python3.11/site-packages (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/maddonk/anaconda3/lib/python3.11/site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/maddonk/anaconda3/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/maddonk/anaconda3/lib/python3.11/site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/maddonk/anaconda3/lib/python3.11/site-packages (from requests) (2023.11.17)
Collecting package metadata (current_repodata.json): | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
/ DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/osx-arm64/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/osx-arm64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.2
  latest version: 23.10.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.10.0



# All requested packages already installed.

In [62]:
def subdf(df,age,gender):
    df = df[(df["sex"]==gender) & (df["age"]==age)]
    return df

In [104]:
df= pd.read_csv("une_rt_a.tsv.gz",compression="gzip")
girlsdf = df[(df["sex"]=="F") & (df["age"]=="Y15-24")]
womendf=df[(df["sex"]=="F")&(df["age"]=="Y25-54")]
gransdf = df[(df["sex"]=="F") & (df["age"]=="Y55-74")]
boysdf = subdf(df,"Y15-24","M")
mensdf = subdf(df,"Y25-54","M")
granpsdf = subdf(df,"Y55-74","M")
#Extracting years column in order to split it up
expanded_columns = df.iloc[:, -1].str.split('\t', expand=True)

column_name = df.columns[-1].split('\\')[-1]
column_names = column_name.split(" ")
print(column_names)


#deleting colum containing area abbrev since collecting numbers
expanded_columns.__delitem__(0)
expanded_columns.columns = column_names[1:]
df = pd.concat([df.iloc[:, :-1], expanded_columns], axis=1)



df

['time\t2022', '\t2021', '\t2020', '\t2019', '\t2018', '\t2017', '\t2016', '\t2015', '\t2014', '\t2013', '\t2012', '\t2011', '\t2010', '\t2009', '\t2008', '\t2007', '\t2006', '\t2005', '\t2004', '\t2003', '']

,age,unit,sex,\t2021,\t2020,\t2019,\t2018,\t2017,\t2016,\t2015,...,\t2011,\t2010,\t2009,\t2008,\t2007,\t2006,\t2005,\t2004,\t2003,
0,Y15-24,PC_ACT,F,9.5,11.3,10.6,8.1,9.8,9.1,10.7,...,9.6,9.5,9.8,10.5,:,:,:,:,:,:
1,Y15-24,PC_ACT,F,14.4,16.2,15.6,12.3,15.3,18.2 b,18.3,...,19.0,18.9,22.4,22.6,:,:,:,:,:,:
2,Y15-24,PC_ACT,F,10.7 u,15.3 u,17.7,11.9 u,15.7,16.3,21.1,...,30.6,28.1 b,24.4 b,17.8,:,:,:,:,:,:
3,Y15-24,PC_ACT,F,7.5,8.7,8.0,7.2,7.5,8.0,8.4,...,8.0,7.9,8.7 b,:,:,:,:,:,:,:
4,Y15-24,PC_ACT,F,18.5,16.3,12.3,14.3,16.2,22.9,31.8,...,26.7,21.5,17.2,14.0,:,:,:,:,:,:
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2263,Y55-74,THS_PER,T,38,37,29,37,48,45,47,...,88,71,54,:,:,:,:,:,:,:
2264,Y55-74,THS_PER,T,63,76,63,51,48 b,53,53,...,52,50,55,50,:,:,:,:,:,:
2265,Y55-74,THS_PER,T,7,7,6,7,7,9,8,...,6,6,4 u,3 u,:,:,:,:,:,:
2266,Y55-74,THS_PER,T,22,25,22,21,23,26,37,...,40,32 b,31,21,:,:,:,:,:,:
2267,Y55-74,THS_PER,T,:,:,214,254,214,188,171,...,81,85,91,93,:,:,:,:,:,: