# USA Yearly Inflation Rates Data
This data summarises the USA inflation rates by year, where the total increase in percentage is seen, and per month division is visible.

In [1]:
import pandas as pd

#Importing commands

In [2]:

url = "https://www.usinflationcalculator.com/inflation/current-inflation-rates/"
#Scraping the first table in the link and saving to a dataframe
df_list = pd.read_html(url)
if df_list:
    df = df_list[0]
    
    print(df)
else:
    print("No tables found")
df

      0               1    2     3     4     5     6     7     8     9     10  \
0   Year             Jan  Feb   Mar   Apr   May   Jun   Jul   Aug   Sep   Oct
1   2024  Avail. Feb. 13  NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN
2   2023             6.4  6.0   5.0   4.9   4.0   3.0   3.2   3.7   3.7   3.2
3   2022             7.5  7.9   8.5   8.3   8.6   9.1   8.5   8.3   8.2   7.7
4   2021             1.4  1.7   2.6   4.2   5.0   5.4   5.4   5.3   5.4   6.2
5   2020             2.5  2.3   1.5   0.3   0.1   0.6   1.0   1.3   1.4   1.2
6   2019             1.6  1.5   1.9   2.0   1.8   1.6   1.8   1.7   1.7   1.8
7   2018             2.1  2.2   2.4   2.5   2.8   2.9   2.9   2.7   2.3   2.5
8   2017             2.5  2.7   2.4   2.2   1.9   1.6   1.7   1.9   2.2   2.0
9   2016             1.4  1.0   0.9   1.1   1.0   1.0   0.8   1.1   1.5   1.6
10  2015            -0.1  0.0  -0.1  -0.2   0.0   0.1   0.2   0.2   0.0   0.2
11  2014             1.6  1.1   1.5   2.0   2.1   2.1   2.0   1.7   1.7   1.7
12  2013             1.6  2.0   1.5   1.1   1.4   1.8   2.0   1.5   1.2   1.0
13  2012             2.9  2.9   2.7   2.3   1.7   1.7   1.4   1.7   2.0   2.2
14  2011             1.6  2.1   2.7   3.2   3.6   3.6   3.6   3.8   3.9   3.5
15  2010             2.6  2.1   2.3   2.2   2.0   1.1   1.2   1.1   1.1   1.2
16  2009               0  0.2  -0.4  -0.7  -1.3  -1.4  -2.1  -1.5  -1.3  -0.2
17  2008             4.3  4.0   4.0   3.9   4.2   5.0   5.6   5.4   4.9   3.7
18  2007             2.1  2.4   2.8   2.6   2.7   2.7   2.4   2.0   2.8   3.5
19  2006             4.0  3.6   3.4   3.5   4.2   4.3   4.1   3.8   2.1   1.3
20  2005             3.0  3.0   3.1   3.5   2.8   2.5   3.2   3.6   4.7   4.3
21  2004             1.9  1.7   1.7   2.3   3.1   3.3   3.0   2.7   2.5   3.2
22  2003             2.6  3.0   3.0   2.2   2.1   2.1   2.1   2.2   2.3   2.0
23  2002             1.1  1.1   1.5   1.6   1.2   1.1   1.5   1.8   1.5   2.0
24  2001             3.7  3.5   2.9   3.3   3.6   3.2   2.7   2.7   2.6   2.1
25  2000             2.7  3.2   3.8   3.1   3.2   3.7   3.7   3.4   3.5   3.4

     11   12    13
0   Nov  Dec   Ave
1   NaN  NaN   NaN
2   3.1  3.4   4.1
3   7.1  6.5   8.0
4   6.8  7.0   4.7
5   1.2  1.4   1.2
6   2.1  2.3   1.8
7   2.2  1.9   2.4
8   2.2  2.1   2.1
9   1.7  2.1   1.3
10  0.5  0.7   0.1
11  1.3  0.8   1.6
12  1.2  1.5   1.5
13  1.8  1.7   2.1
14  3.4  3.0   3.2
15  1.1  1.5   1.6
16  1.8  2.7  -0.4
17  1.1  0.1   3.8
18  4.3  4.1   2.8
19  2.0  2.5   3.2
20  3.5  3.4   3.4
21  3.5  3.3   2.7
22  1.8  1.9   2.3
23  2.2  2.4   1.6
24  1.9  1.6   2.8
25  3.4  3.4   3.4

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Year,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,Ave
1,2024,Avail. Feb. 13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023,6.4,6.0,5.0,4.9,4.0,3.0,3.2,3.7,3.7,3.2,3.1,3.4,4.1
3,2022,7.5,7.9,8.5,8.3,8.6,9.1,8.5,8.3,8.2,7.7,7.1,6.5,8.0
4,2021,1.4,1.7,2.6,4.2,5.0,5.4,5.4,5.3,5.4,6.2,6.8,7.0,4.7
5,2020,2.5,2.3,1.5,0.3,0.1,0.6,1.0,1.3,1.4,1.2,1.2,1.4,1.2
6,2019,1.6,1.5,1.9,2.0,1.8,1.6,1.8,1.7,1.7,1.8,2.1,2.3,1.8
7,2018,2.1,2.2,2.4,2.5,2.8,2.9,2.9,2.7,2.3,2.5,2.2,1.9,2.4
8,2017,2.5,2.7,2.4,2.2,1.9,1.6,1.7,1.9,2.2,2.0,2.2,2.1,2.1
9,2016,1.4,1.0,0.9,1.1,1.0,1.0,0.8,1.1,1.5,1.6,1.7,2.1,1.3
10,2015,-0.1,0.0,-0.1,-0.2,0.0,0.1,0.2,0.2,0.0,0.2,0.5,0.7,0.1
11,2014,1.6,1.1,1.5,2.0,2.1,2.1,2.0,1.7,1.7,1.7,1.3,0.8,1.6
12,2013,1.6,2.0,1.5,1.1,1.4,1.8,2.0,1.5,1.2,1.0,1.2,1.5,1.5
13,2012,2.9,2.9,2.7,2.3,1.7,1.7,1.4,1.7,2.0,2.2,1.8,1.7,2.1
14,2011,1.6,2.1,2.7,3.2,3.6,3.6,3.6,3.8,3.9,3.5,3.4,3.0,3.2
15,2010,2.6,2.1,2.3,2.2,2.0,1.1,1.2,1.1,1.1,1.2,1.1,1.5,1.6
16,2009,0,0.2,-0.4,-0.7,-1.3,-1.4,-2.1,-1.5,-1.3,-0.2,1.8,2.7,-0.4
17,2008,4.3,4.0,4.0,3.9,4.2,5.0,5.6,5.4,4.9,3.7,1.1,0.1,3.8
18,2007,2.1,2.4,2.8,2.6,2.7,2.7,2.4,2.0,2.8,3.5,4.3,4.1,2.8
19,2006,4.0,3.6,3.4,3.5,4.2,4.3,4.1,3.8,2.1,1.3,2.0,2.5,3.2
20,2005,3.0,3.0,3.1,3.5,2.8,2.5,3.2,3.6,4.7,4.3,3.5,3.4,3.4
21,2004,1.9,1.7,1.7,2.3,3.1,3.3,3.0,2.7,2.5,3.2,3.5,3.3,2.7
22,2003,2.6,3.0,3.0,2.2,2.1,2.1,2.1,2.2,2.3,2.0,1.8,1.9,2.3
23,2002,1.1,1.1,1.5,1.6,1.2,1.1,1.5,1.8,1.5,2.0,2.2,2.4,1.6
24,2001,3.7,3.5,2.9,3.3,3.6,3.2,2.7,2.7,2.6,2.1,1.9,1.6,2.8
25,2000,2.7,3.2,3.8,3.1,3.2,3.7,3.7,3.4,3.5,3.4,3.4,3.4,3.4

In [4]:
df['Average'] = df.iloc[:, 1:-1].mean(axis=1, skipna=True)
df

TypeError: can only concatenate str (not "int") to str

In [3]:
df.to_csv("../Data/usa_yearly_inflation_rates.csv", index=False)
#Saving the data to a CSV file